In [33]:
import mxnet as mx
from mxnet import ndarray as nd
from mxnet import autograd as ag

In [28]:
x = nd.zeros((2,3),dtype='uint8')
x


[[0 0 0]
 [0 0 0]]
<NDArray 2x3 @cpu(0)>

In [62]:
x = nd.random_normal(shape=(2,3))
x.T


[[-0.54594457 -0.45138445]
 [-1.771029    0.54144019]
 [-2.35562968  0.57938355]]
<NDArray 3x2 @cpu(0)>

In [30]:
y = x[:,0]
y


[ 1.16307867  0.7740038 ]
<NDArray 2 @cpu(0)>

In [36]:
y.shape

(2,)

In [37]:
y.asnumpy()

array([ 1.16307867,  0.7740038 ], dtype=float32)

In [40]:
y.as_in_context(mx.cpu(0))


[ 1.16307867  0.7740038 ]
<NDArray 2 @cpu(0)>

In [43]:
y.context

cpu(0)

In [53]:
nd.take(y,nd.array([0]))


[ 1.16307867]
<NDArray 1 @cpu(0)>

In [55]:
x = nd.array([1.2])

In [57]:
x.asscalar()

1.2

In [58]:
y.T


[ 1.16307867  0.7740038 ]
<NDArray 2 @cpu(0)>

In [59]:
y.T


[ 1.16307867  0.7740038 ]
<NDArray 2 @cpu(0)>

In [60]:
y


[ 1.16307867  0.7740038 ]
<NDArray 2 @cpu(0)>

In [64]:
y = nd.random_normal(0, 1, shape=(3, 4))
y


[[ 0.41016445 -0.02261727  0.5712682   0.57461417]
 [-2.7579627   1.4661262   1.07628     0.68629038]
 [-0.61413258  0.35496104  1.83076489  1.07316959]]
<NDArray 3x4 @cpu(0)>

In [65]:
nd.exp(y)


[[ 1.50706565  0.97763658  1.77051103  1.77644503]
 [ 0.06342085  4.33241987  2.93374562  1.98633337]
 [ 0.54111004  1.42612505  6.23865652  2.9246347 ]]
<NDArray 3x4 @cpu(0)>

In [66]:
help(nd.exp)

Help on function exp in module mxnet.ndarray:

exp(data=None, out=None, name=None, **kwargs)
    Returns element-wise exponential value of the input.
    
    .. math::
       exp(x) = e^x \approx 2.718^x
    
    Example::
    
       exp([0, 1, 2]) = [inf, 1, 0.707]
    
    
    
    Defined in src/operator/tensor/elemwise_unary_op.cc:L420
    
    Parameters
    ----------
    data : NDArray
        The input array.
    
    out : NDArray, optional
        The output NDArray to hold the result.
    
    Returns
    -------
    out : NDArray or list of NDArrays
        The output of this function.



In [70]:
x = nd.arange(3)
x


[ 0.  1.  2.]
<NDArray 3 @cpu(0)>

In [73]:
x.reshape((1,2))


[[ 0.  1.]]
<NDArray 1x2 @cpu(0)>